/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package pricedisplay;

import java.text.DecimalFormat;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    private static final DecimalFormat df = new DecimalFormat("0.00");

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    String priceDisplay(String item, Double price) {
        String iterVar = "The price for item: "+item +" is " + df.format(price);
        return iterVar;
    }
}
