/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pricedisplay;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void priceDisplaytest() {
        App testClass = new App();
        assertEquals("Testing the pricedisplay function", String.valueOf("The price for item: icecream is 3.00"),testClass.priceDisplay("icecream",3.00));
    }
}
