/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mountatin;

public class App {
        public static void main(String[] args) {

            Forest forest = new Forest();
            forest.createForest();

        }
      
}
